"""test

Revision ID: 4cd0a3650519
Revises: abdcabcd484e
Create Date: 2025-07-09 13:45:27.754170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cd0a3650519'
down_revision: Union[str, Sequence[str], None] = 'abdcabcd484e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('tituloOriginal', sa.String(), nullable=False),
    sa.Column('capa', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('avaliacao', sa.Float(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('generos', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('diretor', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('avaliacoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('filme_id', sa.String(), nullable=False),
    sa.Column('comentario', sa.String(), nullable=False),
    sa.Column('quant', sa.Float(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacoes')
    op.drop_table('users')
    op.drop_table('filmes')
    # ### end Alembic commands ###
