"""adicionar coluna media no usuario

Revision ID: c57965fcfe32
Revises: fc33d1aaf661
Create Date: 2025-07-15 14:02:43.975017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57965fcfe32'
down_revision: Union[str, Sequence[str], None] = 'fc33d1aaf661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('media', sa.Float(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'media')
    # ### end Alembic commands ###
